### ISSUE TITLE
Trouble adapting

### ISSUE THREAD

**Issue by theednaffattack** [iaincollins/nextjs-starter#34] opened 2017-06-21 18:34 UTC
I'm attempting to adapt this into two versions since I can't use ORM2 (it can't seem to connect to mLab):
1 - a version that uses mongoose, and
2 - a version that uses sequelize

The sequelize version will probably be easier for me since it's similar to ORM, but I'm having major trouble figuring out how to incorporate mongoose.

Is there anything you can suggest as a pointer? I've been using [this post](http://thecodebarbarian.com/building-a-nextjs-app-with-mongodb.html) as a guide but there's just enough difference to make things difficult (for me anyway).

I thank you for coming up with this. I think you've done a great job.

I was hoping to get my code ship-shape and plan to submit it to the Next.js examples since I know a lot of node devs like MongoDB/mongoose for NoSQL, and sequelize for relational DBs.

**Comment by theednaffattack** [comment] 2017-06-21 22:46
Ah, sorry I was able to work out my issues with ORM2 and now I'm up and running. I'd still like to work out a mongoose solution but it can wait.

Thanks for all your hard work.

**Comment by iaincollins** [comment] 2017-06-21 22:46
I'm currently using Mongo DB (on mLab) wth the same code, with some small modifications on a couple of projects - your right it does need a couple of updates.

Issue #32 is about adding these to this project. I'll see if I can put the changes in soon.

The changes were very small but not very obvious as debugging passport can be confusing. I think the biggest issue was re-writing the orm2 queries in passport.js at it didn't handle query for _id instead of id automatically (which I took for granted it would handle…).

If anyone wants to suggest a better orm layer am happy to look at others! Maybe a better approach is to ask people to just pass create, find and update methods for users?

**Comment by iaincollins** [comment] 2017-06-21 22:48
Oh glad it's working for you! Regarding orm2 and mLab, yes I ran into that too. The problem seems to be orm doesn't know how to handle mongo connection strings with multiple hostnames in them.

With a single hostname (as with a free sandbox DB) it's fine, but with any of the paid plans the connection string has multiple servers in the URL for failover, if you take one out it should be okay with orm2 (but will still need the updated passport file).

**Comment by astenmies** [comment] 2017-07-10 14:20
Solution:

The trick for using mlab is just to replace all
`user.id` to `user._id`
and all
`profile.id` to `profile._id`

For the rest, it works like charm. Thanks Ian!

**Comment by iaincollins** [comment] 2017-10-16 13:23
Just to update this issue and close it off, the ORM module has been removed (as it didn't really work well as intended) and happy to say this isn't necessary any more!

This project now supports MongoDB out of the box and defaults to using a temporary in-memory database that works like MongoDB if no database is configured yet.

Additionally, `userDbKey` is now configurable option when setting up the routes with `auth.js` (and is passed through to `passport-strategies.js`) with a default value of `_id`, so it will "just work' on MongoDB and other data stores that support MongoDB API syntax.

**Closed by iaincollins** 2017-10-16 13:23 UTC
Labels: enhancement
