### ISSUE TITLE
win .env

### ISSUE THREAD

**Issue by Naranbat1123** [iaincollins/nextjs-starter#80] opened 2018-04-25 10:57 UTC
node v8.11.1 npm 5.6.0 npm run dev failed 
NODE_ENV=development PORT=3000 node index.js
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

**Comment by iaincollins** [comment] 2018-05-05 14:34
I think this is a duplicate of #75 (I assume is happening on Windows?) but please do comment if not.

(I think there is also another ticket about this somewhere…)

**Closed by iaincollins** 2018-05-05 14:34 UTC
