### ISSUE TITLE
How to protect routes?

### ISSUE THREAD

**Issue by Kryten0807** [iaincollins/nextjs-starter#12] opened 2017-02-20 15:49 UTC
First, thanks for putting this together. It looks very much like what I need (and what I was about 1/3 of the way through putting together).

I do have one question, though. I didn't see any examples in the project of how to protect a route from access by unauthenticated users. Maybe I overlooked it?

I've tried a couple of things, mostly around checking the `props.session` value in various methods (`constructor`, `render`, `getInitialProps`) of the page component. These work, but there's an annoying flicker as the page is rendered and then the router is redirected to the `/auth/signin` page. I *could* do some conditional rendering (eg. an unauthorized message) if the user is not authorized, but there's still going to be that moment where the message is rendered and then the transition is made to the new page.

Thanks for your help!

**Comment by iaincollins** [comment] 2017-02-22 16:50
Thanks and you're welcome!

I haven't actually got round to doing a page which shows this next, but that's the next feature on the list.

I think there are a few ways to do this. In your page check props.session.user on page load, which you could do like this:

````javascript
export default class extends Page {
  static async getInitialProps({req}) {
    // Inherit standard props from the Page (i.e. with session data)
    let props = await super.getInitialProps({req})

    // If user is not signed in then redirect to access denied URL
    if (!props.session.user) {
      this.props.url.push('/access-denied')
    }

    return props
  }

  render() {
    return(
      <Layout session={this.props.session}>
        <p>Some content</p>
      </Layout>
    )
  }
}
````

Alternatively, You could instead extend the Layout and add an option like authRequired="true" and have it render a different "Access Denied" view if the option is specified and props.session.user is not set.

I think I might do the latter when I come to do it as it's less code to manage over all.

**Comment by Kryten0807** [comment] 2017-02-22 17:18
Thanks for your feedback. I did something similar to what you described, except in the `Page` component:

    import React from 'react';
    import Router from 'next/router';
    import Session from './session';

    export default class extends React.Component {

        static async getInitialProps({req}) {
            const sessionObject = new Session({ req });

            return { session: await sessionObject.getSession() };
        }

        constructor(props) {
            super(props);

            if (this.hasAccess && !this.hasAccess() && props.url) {
                props.url.push('/auth/signin');
            }
        }
    }

The idea here is that if I have a page I want to protect, I add a `hasAccess` method which checks the user object in `this.props.session` and decides whether the current user can access it or not. If the user is not allowed to access the page, they get redirected to the login page.

I've done this for one page while I'm playing with the framework, and the `hasAccess` method looks like this:

    hasAccess() {
        return this.props.session && this.props.session.user;
    }

You could easily implement an access control in the `hasAccess` function, perhaps going so far as to make it asynchronous and querying the server.

Let me know if you see problems with this approach - authentication is an area where I don't have a lot of experience & I want to make sure I'm doing it right!

**Comment by iaincollins** [comment] 2017-02-22 18:23
Hey thanks for sharing! That's really interesting and can see working well you have pages with different permissions levels in particular (e.g. to different groups / levels of user).

I'll leave this open till I've done something that implements restricting access.

**Comment by hellais** [comment] 2017-05-16 13:56
I am not sure if I should be opening another ticket, but I think it's also relevant to this discussion.

I suspect that the use of `getInitialProps` for creating the `session` property is not very robust. The issue is that `getInitialProps` will only be called on the server-side on the first page load and then called subsequently when you click on `Links` (as stated in the next.js docs: https://github.com/zeit/next.js/#fetching-data-and-component-lifecycle).
This means that if you use `getInitialProps` to populate the `session` property you will actually only have it set when it's not the first page load.

@iaincollins do you have suggestions on ways around this?

**Comment by jth0024** [comment] 2017-06-06 20:06
@hellais I'm not sure that I understand your reasoning. If `getInitialProps` is always called on the server-side, and every page extends the Page component, shouldn't session always be defined?

**Comment by hellais** [comment] 2017-06-06 20:12
>  If getInitialProps is always called on the server-side, and every page extends the Page component, shouldn't session always be defined?

No, because server-side rendering is not re-run when you navigate to another page from a server side rendered page, but instead it's only rendered in the client hence `getInitialProps` is never called.

**Comment by iaincollins** [comment] 2017-06-07 22:48
To expand on my earlier option, the session object is passed to the ```<Layout>``` on every page so a really easy way to do this with Universal auth is to pass something like a ```loginRequired``` option to the Layout:

```
<Layout session={this.props.session} loginRequired>
  <p>My protected page</p>
</Layout>
```

In the layout you can then just do something like this in the render() method to either show an access denied message (and/or login box) or just render normally:

```
if (this.props.loginRequired && (!this.props.session || !this.props.session.user)) {
  return(<div>Access Denied</div>)
} else {
  return (<div>{this.props.children}</div>)
}
```

You could of course equally pass something like list of groups that the user needs to be in.

I'll be updating the example with an implementation of this for reference as I'm actually using it in another project.

@hellais I'm not sure what you are asking exactly, but yes feel free to raise a ticket.

**Comment by bresson** [comment] 2017-08-02 19:16
@iaincollins Have the examples been updated to demonstrated protected routes? Thank you.

**Comment by jth0024** [comment] 2017-08-10 11:35
@hellais Look at the Session class. In the constructor, the session object is pulled off the req server-side or from localStorage client side. This is only to pre-populate the session object. If you look at the getSession method in the Session class, you can see that it will actually perform an HTTP request to get a new session if _session is expired or undefined. Since getInitialProps always returns the result of session.getSession, this is a robust solution. Next JS calls getInitialProps during the first server-side render AND for every client-side route transition, so props.session will always be defined. The key is that we don't  need server-side rendering to ensure that the session is up to date.

**Comment by brandones** [comment] 2017-08-15 09:02
@bresson At present, any page can be accessed from client-side by opening your browser's Javascript console and executing `window.next.router.push('/the/page/i/want')`. The server will still require authentication if that page makes calls to it. i.e., pages cannot be protected, but data can.

**Comment by bresson** [comment] 2017-08-17 01:07
@brandones thank you for your comment. I think we're basically discussing the same thing but using different terms -- how to authenticate / authorize data access based on certain routes. As far as I can see, Next.js still requires some sort of client authentication ( token based, etc ) as getInitialProps and props.session are browser approaches. It appears a server based approach (API ) requires a full page refresh?

**Comment by iaincollins** [comment] 2017-10-16 13:53
This a great reference for folks but closing this off now as the project now has an example of this at https://nextjs-starter.now.sh/auth/profile

The example isn't great, as it's not entirely clear off the bat - the page is profile management page, so it does other things - but will split off that aspect of functionality into a separate page as an example.

**Closed by iaincollins** 2017-10-16 13:53 UTC
Labels: question

**Comment by HelloEdit** [comment] 2018-02-25 12:16
"Page not found" can you update the link please @iaincollins ?

**Comment by ooade** [comment] 2018-06-18 20:38
Asides that @HelloEdit, it means we'll have to keep repeating the static thingy on all pages? @iaincollins ?

**Comment by ooade** [comment] 2018-06-18 20:48
Well, I think with the inclusion of the [custom app](https://github.com/zeit/next.js#custom-app) introduced in next6 (i think), it can just be done over there and necessary props could be passed to the Component.
