### ISSUE TITLE
re: next build hangs

### ISSUE THREAD

**Issue by UltraFlux** [iaincollins/nextjs-starter#82] opened 2018-05-25 06:13 UTC
git clone https://github.com/iaincollins/nextjs-starter.git
npm install
npm run dev

> nextjs-starter@6.0.3 postinstall /www/clients/nextjs/nextjs-starter
> next build 

waiting, nothing past this point

any thoughts?

**Comment by UltraFlux** [comment] 2018-05-25 17:48
node 9.11.1
npm 6.0.0
Linux 4.4.0-17134-Microsoft #48-Microsoft Fri Apr 27 18:06:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by iaincollins** [comment] 2018-05-25 18:04
I don't have a Windows system to hand at the minute but I did try with node `9.11.1` on a Unix system and didn't run any problems.

Sometimes there are unexpected issues with Windows and packages/modules for Node and has been the cause of a few previous issues.

Could you try two different things:

1) Doing `npm run dev` then just visiting http://localhost:3000 in the browser (in case it's working, but the terminal output is being squashed).

If that doesn't work:

2) Doing `npm build` then `npm start` and seeing what happens then (it should start a service at http://localhost:80).

**Comment by iaincollins** [comment] 2018-05-25 18:06
Oh yes, see also https://github.com/iaincollins/nextjs-starter/issues/75 and any other issues that relate to Windows in case they are relevant. Windows support has fallen by the way side a bit and needs looking at.

**Comment by UltraFlux** [comment] 2018-05-25 18:07
Personally, this is the first windows based issue i've run into using npm and node. I will review your notes.

**Comment by iaincollins** [comment] 2018-05-25 21:42
Closing as seems to be a duplicate of other issues specific to running Windows.

**Closed by iaincollins** 2018-05-25 21:42 UTC

**Comment by UltraFlux** [comment] 2018-05-25 22:46
note that the following worked, which is likely sufficient for development
**npm run dev**
